- name: souscription Redhat
  hosts: "{{ vmsgroup }}"
  remote_user: ansible
  become: True
  vars_files: all.profiles.vars.yml

  tasks:
    - name: modification rhsm.conf - proxy hostname
      ansible.builtin.replace:
        path: /etc/rhsm/rhsm.conf
        regexp: '^proxy_hostname =.*$'
        replace: 'proxy_hostname = {{ proxy_url }}'
      
    - name: modification rhsm.conf - proxy port
      ansible.builtin.replace:
        path: /etc/rhsm/rhsm.conf
        regexp: '^proxy_port =.*$'
        replace: 'proxy_port = {{ proxy_port }}'
      
    - name: souscrire
      command: subscription-manager register --username {{ rhsm_user }} --password {{ rhsm_pass }} --auto-attach --force

#    - name: repository standard
#      command: subscription-manager repos --enable="rhel-7-server-rpms"
#
#    - name: repository optional
#      command: subscription-manager repos --enable="rhel-7-server-optional-rpms"
#
#    - name: repository extras
#      command: subscription-manager repos --enable="rhel-7-server-extras-rpms"
