- hosts: "{{ vmsgroup }}"
  user: ansible
  become: True
  tasks:
    - name: Install package "{{ package }}"
      yum:
        name: "{{ package }}"
        state: present
        update_cache: True
      when: ansible_facts['os_family'] == "Redhat"

    - name: Install package "{{ package }}"
      apt:
        name: "{{ package }}"
        state: present
        update_cache: True
      when: ansible_facts['os_family'] == "Debian"



