- hosts: "{{ vmsgroup }}"
  user: ansible
  become: True
  tasks:
#    - include_vars: "{{ awd }}/variables.yml"
    - name: Install package "{{ package }}"
      apt:
        name: "{{ package }}"
        state: present
        update_cache: True

