 ln -s ../common/ansible/
 ln -s ../common/dns/
 ln -s ../common/login.gp.auto.tfvars 
 ln -s ../common/main.tf
 ln -s ../common/output.py 
 ln -s ../common/output.sh 
 ln -s ../common/variables.auto.tfvars 
 ln -s ../common/variables.
 ln -s ../common/vm
